name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Create and Activate Conda Environment
        run: |
          conda init
          conda create -n build_env python=3.10 -y
          conda activate build_env
      - name: Install Dependencies
        run: |
          conda env update --file environment.yml --name build_env
      - name: Lint with flake8
        run: |
          conda install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          conda install pytest
          pytest
      - name: Deactivate Conda Environment
        run: conda deactivate
